version: "3.11"

services:
  db:
    image: postgres
    env_file:
      - ./.env.dev
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/dat

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --no-input --username admin --email admin@example.com && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sinai_bot
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=sianibotalex123S
    env_file:
      - ./.env.dev
    depends_on:
      - db

  telegram:
    build: .
    command: python -m telegram_bot.bot
    volumes:
      - .:/sinai_bot
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: