services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sinai_bot
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_db

  telegram:
    build: .
    command: python -m telegram_bot.bot
    volumes:
      - .:/sinai_bot
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_db

networks:
  postgres_db:
    external: true