# Generated by Django 4.2.7 on 2023-11-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('tg_user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('language_code', models.CharField(blank=True, help_text="Telegram client's lang", max_length=8, null=True)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'tg_user',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextLanguages',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('language_code', models.CharField(help_text='language code', max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'text_languages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SinaiUser',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='telegram_bot.telegramuser')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sinai User',
                'verbose_name_plural': 'Sinai Users',
                'db_table': 'sinai_user',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuLevel',
            fields=[
                ('menu_level_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Menu Level ID')),
                ('level_name', models.CharField(max_length=256)),
                ('keyboard_type', models.CharField(choices=[('inline', 'Inline Keyboard'), ('reply', 'Reply Keyboard')], default='inline', max_length=10)),
                ('developed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level', to='telegram_bot.menulevel')),
            ],
            options={
                'verbose_name': 'Menu Level',
                'verbose_name_plural': 'Menu Levels',
                'db_table': 'menu_level',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name_of_execution_function', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position_in_row', models.IntegerField(blank=True, null=True)),
                ('position_in_col', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.textlanguages')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.menulevel')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBotText',
            fields=[
                ('data_bot_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('id_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.textlanguages')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'db_table': 'data_bot_text',
                'ordering': ['created_at'],
            },
        ),
    ]
