# Generated by Django 4.2.7 on 2023-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_menuitem_position_in_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulevel',
            name='menu_text_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
