# Generated by Django 4.2.7 on 2023-12-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_menulevel_menu_text_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulevel',
            old_name='menu_text_id',
            new_name='level_text_id',
        ),
    ]
