# Generated by Django 4.2.7 on 2023-12-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_menuitem_text_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_reply_items', to='telegram_bot.menulevel'),
        ),
    ]
